stages:
 - test
 - notify

variables:
 TEST_VALUE: "10"

test_condition:
 stage: test
 image: alpine:latest
 script:
  - apk add --no-cache curl bash
  - |
    a=5
    b=${TEST_VALUE}
    
    echo "Testing: a=$a, b=$b"
    
    if [[ $b -ge $a ]]; then
     echo "SUCCESS: $b >= $a"
     echo "STATUS=success" > status.env
    else
     echo "FAILED: $b < $a"
     echo "STATUS=failed" > status.env
     exit 1
    fi
 artifacts:
  paths:
   - status.env
  expire_in: 1 hour

telegram_notify:
 stage: notify
 image: alpine:latest
 script:
  - apk add --no-cache curl
  - |
    if [ -f status.env ]; then
    STATUS="success" 
    else
    STATUS="failed"
    fi
    
    if [ "$STATUS" == "success" ]; then
    MESSAGE=" Pipeline SUCCESS"
    fi
    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
    -d "chat_id=${TELEGRAM_CHAT_ID}" \
    -d "text=${MESSAGE}" \
    -d "parse_mode=HTML"

    echo "Telegram notification sent"
 needs:
  - test_condition
 when: always
 variables:
   TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
   TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
   
